name: AdvancementNametag
version: '${project.version}'
main: me.xingyan.advancementnametag.AdvancementNametag
api-version: 1.21
author: xy
folia-supported: true
softdepend: [PlaceholderAPI]
commands:
  tags:
    description: open a gui to set the nametag
    usage: /<command> [reload|view <player>]
permissions:
  advancementnametag.use:
    description: Allows players to open the tags GUI
    default: true
  advancementnametag.admin:
    description: Allows access to admin subcommands (reload, view)
    default: op
